# Generated by Django 5.0.1 on 2024-01-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='listing',
            field=models.BooleanField(default=True),
        ),
    ]
