# Generated by Django 5.0.1 on 2024-01-21 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0002_ticker_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorsRuleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=30)),
                ('goal_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.indicators')),
                ('rule_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.indicatorsruletable')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorsValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('value', models.FloatField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.indicators')),
                ('stock_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.price')),
                ('stock_ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ticker')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.FloatField()),
                ('indicator_rule_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.indicatorsruletable')),
                ('stock_price_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_price', to='stock.price')),
                ('stock_price_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_indicator', to='stock.price')),
                ('stock_price_sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_price', to='stock.price')),
                ('stock_ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ticker')),
            ],
        ),
    ]
